### ISSUE TITLE
Suspected Lock related issue while building paraview

### ISSUE THREAD

**Issue by sherinsugathan** [NAICNO/HPC-Visualization#2]
Paraview build using EasyBuild throwing errors related to locks.
Relevant error log when attempted a `--parallel 4 ` attached below:
[ParaviewBuildError.txt](https://github.com/NAICNO/HPC-Visualization/files/13278302/ParaviewBuildError.txt)

The recipe in use is attached below:
[ParaView-5.11.1-foss-2022b-mpi.eb.txt](https://github.com/NAICNO/HPC-Visualization/files/13278326/ParaView-5.11.1-foss-2022b-mpi.eb.txt)

Note:
1. Attempting a non-parallel build seems to complete more steps than parallel version but encounters the nodejs EAGAIN related errors.

**Comment by Sabryr** [comment]
The message about the lock is not an error. When you compile with EB, to make sure multiple users do not compile at the same time a lock is placed. After completion or the failure the lock is removed. 
I am hitting the same error as in the attachment. I also tried to compile on a GPU node. 

`make[2]: Leaving directory '/fp/homes01/u01/ec-fox-sw/sabryr/software/build/ParaView/5.11.1/foss-2022b-mpi/easybuild_obj'
[ 12%] Built target vtkhdf5_src
make[1]: Leaving directory '/fp/homes01/u01/ec-fox-sw/sabryr/software/build/ParaView/5.11.1/foss-2022b-mpi/easybuild_obj'
make: *** [Makefile:149: all] Error 2
 (at easybuild/software/EasyBuild/4.8.2/lib/python3.9/site-packages/easybuild/tools/run.py:681 in parse_cmd_output)
== 2023-11-07 20:16:33,963 build_log.py:267 INFO ... (took 3 mins 14 secs)
== 2023-11-07 20:16:33,966 filetools.py:2012 INFO Removing lock /fp/homes01/u01/ec-fox-sw/sabryr/software/software/.locks/_fp_homes01_u01_ec-fox-sw_sabryr_software_software_ParaView_5.11.1-foss-2022b-mpi.lock...
== 2023-11-07 20:16:33,967 filetools.py:383 INFO Path /fp/homes01/u01/ec-fox-sw/sabryr/software/software/.locks/_fp_homes01_u01_ec-fox-sw_sabryr_software_software_ParaView_5.11.1-foss-2022b-mpi.lock successfully removed.
== 2023-11-07 20:16:33,967 filetools.py:2016 INFO Lock removed: /fp/homes01/u01/ec-fox-sw/sabryr/software/software/.locks/_fp_homes01_u01_ec-fox-sw_sabryr_software_software_ParaView_5.11.1-foss-2022b-mpi.lock
== 2023-11-07 20:16:33,967 easyblock.py:4277 WARNING build failed (first 300 chars): cmd " make  -j 24 " exited with exit code 2 and output:
/cluster/software/EL9/easybuild/software/CMake/3.24.3-GCCcore-12.2.0/bin/cmake -S/fp/homes01/u01/ec-fox-sw/sabryr/software/build/ParaView/5.11.1/foss-2022b-mpi/ParaView-v5.11.1 -B/fp/homes01/u01/ec-fox-sw/sabryr/software/build/ParaView/5.11.1/f
== 2023-11-07 20:16:33,967 easyblock.py:328 INFO Closing log for application name ParaView version 5.11.1
`

**Comment by Sabryr** [comment]
I do not have a solution for this as I do not see what exactly is the reason.

**Comment by sherinsugathan** [comment]
Hi Sabry!, Thanks for your time looking into this issue. I also couldn't see a specific reason except those lock related messages happening just before the failure messages. That is why I was suspecting the case of unable to acquire locks. I will continue investigating on this.

**Comment by Sabryr** [comment]
Please share if you find anything. My next would be to load all the dependency modules and try to compile Paraview manually.

**Comment by sherinsugathan** [comment]
By doing a more verbose build using `--debug` I found 'unable to call compiler' errors. (logs attached
[unableToCallCompiler.txt](https://github.com/NAICNO/HPC-Visualization/files/13312138/unableToCallCompiler.txt)
)
Thinking of submitting the build as a job and see what happens.

**Comment by Sabryr** [comment]
This is very useful, thank you. I tried building in RAM, that also failed. The reason for this the IO error in your log sometimes is a result ob building on a parallel file system.

`
 eb --prefix=/.../software --buildpath=/dev/shm --parallel=24 --robot ParaView-5.11.1-foss-2022b-mpi.eb
`

**Comment by Sabryr** [comment]
I think I have narrowed to down to `ParaView-v5.11.1/VTK/ThirdParty/vtkm/vtkvtkm/vtk-m/vtkm/exec/cuda/internal/ExecutionPolicy.h`  .  

Need to find the compatibility issue when compiling the following file
`..ParaView/5.11.1/foss-2022b-mpi/ParaView-v5.11.1/VTK/ThirdParty/vtkm/vtkvtkm/vtk-m/vtkm/cont/ArrayCopy.cxx`

**Comment by sherinsugathan** [comment]
Thank you. I hit the same issue. I guess you might have seen those thrust related errors.  I think a potential fix would be to use the attached recipe+patches to fix those compilation issues. Now, I am facing some EasyBuild crash errors.

[RecipeUpdate.zip](https://github.com/NAICNO/HPC-Visualization/files/13322925/RecipeUpdate.zip)

**Comment by sherinsugathan** [comment]
UPDATE: I was able to build Paraview directly using cmake for the same foss2022b toolchain and CUDA 12.
For later reference of enabled configuration options, I am attaching the CmakeCache. [CMakeCache.txt](https://github.com/NAICNO/HPC-Visualization/files/13369669/CMakeCache.txt)

The following modules were manually loaded for the build process to finish successfully.
[ModulesLoaded.txt](https://github.com/NAICNO/HPC-Visualization/files/13369680/ModulesLoaded.txt)

Now I will again give a try to EasyBuild way of building in light of the above configuration options.

**Comment by Sabryr** [comment]
Well done. I can not see which cuda compatibility is set in the cmake file. 
https://developer.nvidia.com/cuda-gpus

**Comment by sherinsugathan** [comment]
> Well done. I can not see which cuda compatibility is set in the cmake file. https://developer.nvidia.com/cuda-gpus

It is not inside the cmake file. So I tried setting it outside. You can use -DCMAKE_CUDA_ARCHITECTURES=90 I think.
Also, for the migtest partition, I was getting a message (ReqNodeNotAvail, May be reserved for other job). I don't know if my job(#368075) will enter into a running stage or not. My successful build was targeted for A100 because I was trying to resolve some compilation issues. When I tried starting paraview, I got some runtime dependency issues as well, and I am trying to address those issues now.

**Comment by Sabryr** [comment]
for "ReqNodeNotAvail" means some mismatching requests I will send some parameters in chat

**Comment by sherinsugathan** [comment]
The original build issues are resolved now. So closing this issue.
Attached a working version of easybuild recipe (+patch) that uses CUDA 12.
[ParaviewCUDA12_MPI_eb.zip](https://github.com/NAICNO/HPC-Visualization/files/13858997/ParaviewCUDA12_MPI_eb.zip)
Running paraview via X11 forwarding will not give a direct rendering context that uses NVIDIA.
Need to use TurboVNC in ML nodes for rendering using virtualGL. Issues related to this effort will be tracked in a separate thread as needed.
