### ISSUE TITLE
[ParaView]: Unable to start pvserver application due to missing library.

### ISSUE THREAD

**Issue by sherinsugathan** [NAICNO/HPC-Visualization#4]
1. Start a fox desktop session in EduCloud OnDemand without GPUs.
2. Download https://www.paraview.org/paraview-downloads/download.php?submit=Download&version=v5.13&type=binary&os=Linux&downloadFile=ParaView-5.13.0-RC2-egl-MPI-Linux-Python3.10-x86_64.tar.gz
3. Extract and cd into `ParaView-5.13.0-RC2-egl-MPI-Linux-Python3.10-x86_64/bin`
4. run `./pvserver`

**_Error:_** 
`error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory.`

**_Additional Information:_**
Note that this issue don't happen in ML nodes (probably because the required package is already installed).

**_Potential Solution:_**
Need to install relevant packages inside the desktop provisioned in EduCloud? I am not sure, but `dnf install libxcrypt-compat` might help?

**Comment by sherinsugathan** [comment]
@Sabryr I would like to get some help on this issue. Should I message buzh directly ?

**Comment by Sabryr** [comment]
I will have a meeting with buZh, but this issues is the precompiled binary. We need to find correct libraries to load (that are linked). I will check

**Comment by sherinsugathan** [comment]
Solution: Development can easily continue while running paraview in headless mode. For this, we don't have to start paraview, but instead running pvserver ((no missing lib errors)) is enough. Closing this issue as the blocker is resolved.
